### ISSUE TITLE
Broken for icontract >= 2.4.0

### ISSUE THREAD

**Issue by TeoZosa** [Parquery/sphinx-icontract#23]
`_is_lambda` was renamed to `is_lambda` in Parquery/icontract#178, breaking `sphinx-icontract` for `icontract` versions >= 2.4.0. 

I propose updating the codebase with respect to the rename and constraining `icontract` to >= 2.4.0. 

P.S. Thanks for all the hard work maintaining/improving `hypothesis`, `icontract`, and `hypothesis-icontract`. Integrating them has been a fantastic experience thus far!

**Comment by mristin** [comment]
Btw., if you haven't done so already, please consider giving a star to the project to help it gain some visibility.
