### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Marcel-Pleyer** [Parquery/sphinx-icontract#25]
Hi, first of all thank you for these awesome libraries! 👍 

I noticed, when using sphinx-icontract there were changes (_is_lambda was renamed to is_lambda), which have been fixed in #24  .
But it seems that the version, which includes the fix is not released yet. Or I am missing something?

**Comment by mristin** [comment]
Hi @Marcel-Pleyer ,
You are welcome :).

It is well possible that I simply forgot to make a new release. I'll try to check it this evening.

**Comment by Marcel-Pleyer** [comment]
@mristin thank you for the quick reply! :)

**Comment by mristin** [comment]
@Marcel-Pleyer I released a new patch version and it's on pypi: https://pypi.org/project/sphinx-icontract/

Please apologize for the omission, it slipped on my todo list. I'll close the issue -- please feel free to re-open if there are further problems.

**Comment by mristin** [comment]
(Btw., please consider starring the project on GitHub to give it some visibility.)

**Comment by Marcel-Pleyer** [comment]
@mristin sorry for the late response. Thank you for releasing the patch! Works fine.

Btw: Starred the project, keep up the good work!
